version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql/bot_marketplace
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mysql
      - redis

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bot_marketplace
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  bot:
    build: ./bot
    volumes:
      - ./bot:/app
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql/bot_marketplace
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
  redis_data:

networks:
  se1dhe_network:
    driver: bridge 