"""initial migration

Revision ID: 001
Revises:
Create Date: 2025-03-31

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.String(length=1000), nullable=True),
                    sa.Column('slug', sa.String(length=255), nullable=True),
                    sa.Column('image_url', sa.String(length=255), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('discount_percent', sa.Float(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)

    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('username', sa.String(length=255), nullable=False),
                    sa.Column('hashed_password', sa.String(length=255), nullable=False),
                    sa.Column('telegram_id', sa.String(length=255), nullable=True),
                    sa.Column('full_name', sa.String(length=255), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('is_superuser', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    op.create_table('bots',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('slug', sa.String(length=255), nullable=True),
                    sa.Column('short_description', sa.String(length=500), nullable=True),
                    sa.Column('full_description', sa.Text(), nullable=True),
                    sa.Column('readme_md', sa.Text(), nullable=True),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('discount_percent', sa.Float(), nullable=True),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('preview_image_url', sa.String(length=255), nullable=True),
                    sa.Column('images', sa.JSON(), nullable=True),
                    sa.Column('videos', sa.JSON(), nullable=True),
                    sa.Column('demo_url', sa.String(length=255), nullable=True),
                    sa.Column('features', sa.JSON(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('is_featured', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_bots_id'), 'bots', ['id'], unique=False)
    op.create_index(op.f('ix_bots_slug'), 'bots', ['slug'], unique=True)

    op.create_table('discounts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('code', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(length=255), nullable=True),
                    sa.Column('percent', sa.Float(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('max_uses', sa.Integer(), nullable=True),
                    sa.Column('current_uses', sa.Integer(), nullable=True),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('bot_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
                    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
                    )
    op.create_index(op.f('ix_discounts_id'), 'discounts', ['id'], unique=False)

    op.create_table('orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('order_number', sa.String(length=50), nullable=True),
                    sa.Column('order_type', sa.Enum('bot_purchase', 'custom_bot', name='ordertype'), nullable=False),
                    sa.Column('bot_id', sa.Integer(), nullable=True),
                    sa.Column('custom_requirements', sa.JSON(), nullable=True),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('discount_amount', sa.Float(), nullable=True),
                    sa.Column('final_amount', sa.Float(), nullable=False),
                    sa.Column('status', sa.Enum('pending', 'paid', 'processing', 'completed', 'cancelled', 'refunded',
                                                name='orderstatus'), nullable=True),
                    sa.Column('payment_id', sa.String(length=255), nullable=True),
                    sa.Column('payment_method', sa.String(length=50), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)

    op.create_table('subscriptions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('bot_id', sa.Integer(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)

    op.create_table('bug_reports',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('bot_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('steps_to_reproduce', sa.Text(), nullable=True),
                    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='bugseverity'),
                              nullable=True),
                    sa.Column('status', sa.Enum('new', 'in_progress', 'fixed', 'wont_fix', 'duplicate', 'closed',
                                                name='bugstatus'), nullable=True),
                    sa.Column('admin_notes', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_bug_reports_id'), 'bug_reports', ['id'], unique=False)

    op.create_table('changelogs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('bot_id', sa.Integer(), nullable=False),
                    sa.Column('version', sa.String(length=50), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('changes', sa.JSON(), nullable=True),
                    sa.Column('is_published', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('released_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_changelogs_id'), 'changelogs', ['id'], unique=False)

    op.create_table('notifications',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('notification_type',
                              sa.Enum('system', 'new_bot', 'bot_update', 'order_status', 'subscription', 'bug_report',
                                      'custom', name='notificationtype'), nullable=True),
                    sa.Column('is_read', sa.Boolean(), nullable=True),
                    sa.Column('related_bot_id', sa.Integer(), nullable=True),
                    sa.Column('related_order_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['related_bot_id'], ['bots.id'], ),
                    sa.ForeignKeyConstraint(['related_order_id'], ['orders.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_changelogs_id'), table_name='changelogs')
    op.drop_table('changelogs')
    op.drop_index(op.f('ix_bug_reports_id'), table_name='bug_reports')
    op.drop_table('bug_reports')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_discounts_id'), table_name='discounts')
    op.drop_table('discounts')
    op.drop_index(op.f('ix_bots_slug'), table_name='bots')
    op.drop_index(op.f('ix_bots_id'), table_name='bots')
    op.drop_table('bots')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###