"""Add subscriptions table and update related models

Revision ID: 6885a93abbd1
Revises: e08664d5f59c
Create Date: 2025-04-02 01:07:30.724471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6885a93abbd1'
down_revision: Union[str, None] = 'e08664d5f59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('bots', sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'ACTIVE', 'SUSPENDED', 'DELETED', name='botstatus'), nullable=False))
    op.add_column('bots', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.alter_column('bots', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('bots', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'bots', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'DEVELOPER', 'ADMIN', 'SUPERUSER', name='userrole'), nullable=False))
    op.add_column('users', sa.Column('telegram_username', sa.String(length=255), nullable=True))
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('telegram_id', table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index('telegram_id', 'users', ['telegram_id'], unique=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    op.drop_column('users', 'telegram_username')
    op.drop_column('users', 'role')
    op.drop_column('users', 'full_name')
    op.drop_constraint(None, 'bots', type_='foreignkey')
    op.alter_column('bots', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('bots', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    op.drop_column('bots', 'is_verified')
    op.drop_column('bots', 'status')
    op.drop_column('bots', 'owner_id')
    # ### end Alembic commands ###
